# Generated by Django 3.2.9 on 2021-12-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('is412project', '0002_alter_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(max_length=200),
        ),
    ]
