# Generated by Django 3.2.9 on 2021-12-07 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('is412project', '0005_alter_item_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemQuan', models.IntegerField(default=0)),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('phoneNum', models.IntegerField(max_length=200)),
                ('zipCode', models.IntegerField(default=0)),
                ('ccard', models.IntegerField(default=0)),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='is412project.item')),
            ],
        ),
    ]
