# Generated by Django 3.2.9 on 2021-12-07 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='fname',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='lname',
            new_name='fnameandlname',
        ),
    ]
